import '@/app/globals.css';
import GlobalHeader from '@/components/global/header';
import GlobalPodcastPlayer from '@/components/global/podcast-player';
import PlayerProvider from '@/providers/podcast-player-provider';
import ReactQueryProvider from '@/providers/react-query';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <PlayerProvider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <GlobalHeader />
            {children}
            <GlobalPodcastPlayer />
            <Toaster position="top-center" richColors />
          </body>
        </PlayerProvider>
      </ReactQueryProvider>
    </html>
  );
}
